### ISSUE TITLE
Cant add rcon server of existing instance 

### ISSUE THREAD

**Issue by noideaman** [devinSpitz/PavlovRconWebserver#117]
Have a pavlov server running in a docker container. I can use [Oakraven79/pavlov_rcon_tcl](https://github.com/Oakraven79/pavlov_rcon_tcl) to connect to it
But setting up this web server application fails the same across Arch/arch in wsl/rocky linux 8/ubuntu in docker/the docker-compose container/windows

```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Prepend[TSource](IEnumerable`1 source, TSource element)
   at AspNetCore.Views_PavlovServer_Server.ExecuteAsync() in /PavlovRconWebserver/PavlovRconWebserver/Views/PavlovServer/Server.cshtml:line 36
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
![image](https://user-images.githubusercontent.com/39884745/163278173-86bb975f-77f4-4fad-990e-b2f6590163c1.png)
same error no matter what field is filled out

**Comment by devinSpitz** [comment]
Yeah, the panel will connect over ssh to the server that runs the Pavlov server. If you are inside a docker it will not be possible. My software does not support dockerized Pavlov servers like Vanguard itself doesent support that.

**Comment by devinSpitz** [comment]
But we can talk about that in the discord may we can get it to work but without restart/stop/Update and other features  of servers.

**Comment by noideaman** [comment]
forgot have ssh running in the container on its own port 2222

**Comment by devinSpitz** [comment]
oh ok that makes it more interessting :D ist systemd available there?

**Comment by noideaman** [comment]
no no system d, service works

**Comment by devinSpitz** [comment]
Ah you did not set the server folder path for now xD

**Comment by noideaman** [comment]
i am adding a existing one that is running.

**Comment by devinSpitz** [comment]
So the plus button?: 
![image](https://user-images.githubusercontent.com/69326203/163340565-5c6f20b0-991d-4c47-9e76-5bd55f63ccbd.png)


Everything with a red number is needed do you have set all the vars?: 
![image](https://user-images.githubusercontent.com/69326203/163340712-cbf7cb64-a621-4037-b07d-dd6c0dba1684.png)

**Comment by noideaman** [comment]
yep the plus, and yep have added all settings

**Comment by noideaman** [comment]
ghats new
 ![image](https://user-images.githubusercontent.com/39884745/163341771-16e434cc-c082-4833-a4d7-baf330165b6a.png)

**Comment by devinSpitz** [comment]
yes that a problem xD
it will try systemctl restart ..... and systemctl stop ...... and also makes a sudo file so it does not need to enter the password for this commands.

I would need to make a way to not forse start and stop the server to check if its working.

**Comment by noideaman** [comment]
i can mess with creating bash aliases

**Comment by devinSpitz** [comment]
possible yes  :D I check the return values with regex for some stuff so make sure you succeed in these tests xD

**Comment by devinSpitz** [comment]
Personaly better would be just a simple add with no support of restart stop or update just as monitoring :)

**Comment by devinSpitz** [comment]
Maybe init d support or no monitoring of the service.

**Comment by noideaman** [comment]
awesome thank you

**Comment by noideaman** [comment]
so i did make an init.d script if you wana go from there have an issue with the status command
hopefuly this gives you a start on it. will github my dockerfile soon
```sh
#!/bin/sh

### BEGIN INIT INFO
# Provides:          Pavlov
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example
# Description:       Example start-stop-daemon - Debian
### END INIT INFO

NAME="pavlov"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
APPDIR="/"
APPBIN="/startpavlov.sh"
USER="steam"
GROUP="steam"

# Include functions
set -e
. /lib/lsb/init-functions

start() {
  printf "Starting '$NAME'... "
  start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /run/$NAME.pid --chdir "$APPDIR" --exec "$APPBIN" || true
  printf "done\n"
}

#We need this function to ensure the whole process tree will be killed
killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

stop() {
  printf "Stopping '$NAME'... "
  [ -z `cat /run/$NAME.pid 2>/dev/null` ] || \
  while test -d /proc/$(cat /run/$NAME.pid); do
    killtree $(cat /run/$NAME.pid) 15
    sleep 0.5
  done
  [ -z `cat /run/$NAME.pid 2>/dev/null` ] || rm /run/$NAME.pid
  printf "done\n"
}

status() {
  status_of_proc -p /run/$name.pid /bin/bash /startpavlov.sh && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
```
the contents of startpvalov.sh include everything including updating on startup/restart
```bash
#!/bin/bash
/usr/games/steamcmd +login anonymous +force_install_dir "/home/steam/pavlovserver" +app_update 622970 +exit
/usr/games/steamcmd +login anonymous +force_install_dir "/home/steam/pavlovserver" +app_update 1007 +quit
mkdir -p /home/steam/pavlovserver/pavlovserver/Pavlov/Binaries/Linux/
mkdir -p /home/steam/pavlovserver/.steam/sdk64
chmod +x /home/steam/pavlovserver/pavlovserver/PavlovServer.sh
cp /home/steam/pavlovserver/Steam/steamapps/common/Steamworks\ SDK\ Redist/linux64/steamclient.so /home/steam/pavlovserver/.steam/sdk64/steamclient.so
cp /home/steam/pavlovserver/Steam/steamapps/common/Steamworks\ SDK\ Redist/linux64/steamclient.so /home/steam/pavlovserver/pavlovserver/Pavlov/Binaries/Linux/steamclient.so
cd /home/steam/pavlovserver
./PavlovServer.sh
```

**Comment by noideaman** [comment]
yep got what i needed to work, it builds will add a git repo soon of this combo docker image of the rconwebserver and steamcmd

**Comment by noideaman** [comment]
https://github.com/noideaman/DockerPavlovRcon
added a license file in the repo
https://github.com/noideaman/DockerPavlovRcon/blob/main/pavlov the init.d script
https://github.com/noideaman/DockerPavlovRcon/blob/main/startpavlov.sh < the script init.d calls. you can remove all the chows, i am testing that it works with out that next

**Comment by noideaman** [comment]
So all my scripts look to be clean and the `service pavlov status` command works now
even have one for the pavlovrconwebserver service

**Comment by devinSpitz** [comment]
> So all my scripts look to be clean and the `service pavlov status` command works now
> even have one for the pavlovrconwebserver service

Perfect :) Thanks i will check that out soon :)

**Comment by noideaman** [comment]
Awesome thanks you for this, i am going test this out in my container now

**Comment by noideaman** [comment]
The services are still not being created
when testing it fails and i dont see it trying to log in via ssh at any point

Does the creating a pavlov instance use port 22? the docker service has it running on port 2222 for internal access
![Screenshot 2022-07-10 at 16-46-41 Pavlov Rcon Webserver](https://user-images.githubusercontent.com/39884745/178165237-9fd5fd65-d35c-49de-b837-391d60e34c78.png)


I have port 2222 defined on the upper RCON instance
![Screenshot 2022-07-10 at 16-45-50 Pavlov Rcon Webserver](https://user-images.githubusercontent.com/39884745/178165293-7c1a3f61-712f-46f2-9bb6-6949a12d7650.png)


the error after about 5 minutes
![Screenshot 2022-07-10 at 16-56-20 Pavlov Rcon Webserver](https://user-images.githubusercontent.com/39884745/178165321-a21387d3-b768-4ba8-9f20-c6e365d916bf.png)
output of pavlov this one had a different error
[pavlovrconoutput.txt](https://github.com/devinSpitz/PavlovRconWebserver/files/9080030/pavlovrconoutput.txt)

![unhandled](https://user-images.githubusercontent.com/39884745/178165490-67852717-9a12-4d37-9745-b2bcb1f23b00.png)
